### ISSUE TITLE
Windows Device Removal Listener still not working

### ISSUE THREAD

**Issue by AlexBGar** [nyholku/purejavahidapi#28]
Hi
Thanks for working on the deviceRemovalListener. There is an improvement but I still cannot get it to work properly. Attached is the version of Example2 I am using. Previously, on removing my devive, I got an error message:
_      GetOverlappedResult failed with GetLastError()==1167
       ReadFile failed with GetLastError()==0 
Now, with the latest version, the transfers just stop with no error message and no Device Removal message.
I am using Netbeans and Java 8.60 on a Windows 10 machine
Regards
Alex

[Example2.zip](https://github.com/nyholku/purejavahidapi/files/182123/Example2.zip)

**Comment by nyholku** [comment]
Well, that is unfortunate because it is working for me on my Windows 7. I suggest you try to debug the DeviceRemovalHandler class by setting breakpoints in there to see if you get any messages from the OS. Even if the code maybe byzantine (the device handling in Windows is!) you should at least be able to see if anything is happening. This could be Windows 10 specific and I don't have (nor intend to have any time soon) Windows 10 so it is hard for me to debug this.

**Comment by AlexBGar** [comment]
I'll try it on my old Vista machine and let you know what happens.

Alex

**Comment by AlexBGar** [comment]
Tests on purejavahidapi
Using version 0.0.1 (possibly modified to account for 0 length transfers are per instructions)
My simple program will list the devices on my system and run my device but crashes when the device is removed.
Using version 0.0.2 as downloaded 0n 21/03/16, both List and Run fail.
The program I use and the error printouts are in the attached zip file. 
Also
I cannot get Example 2 to work on my Vista machine. No point in pursuing this.
I tried creating a project combining Example 2 with the purejavahidapi project. Netbeans did not detect any errors in doing this but the program would not detect my device.
[pureJavaHID.zip](https://github.com/nyholku/purejavahidapi/files/184285/pureJavaHID.zip)

**Comment by nyholku** [comment]
I found a dangling reference to jna platform.jar so I removed that. I doubt that will solve your problem but worth a try. It is strange that you did not get any exception about the missing platform.jar ...

**Comment by AlexBGar** [comment]
You are right, it doesn't solve my problem. With all the different versions of purejavahipapi and jna, I have gone through various combinations and can make the following observations:

My application requires jna-platform.jar in th library path
purejavaHIDapi.jar must not have a version appended (I tried adding  version number 0.0.2 to avoid confusion)
Using different versions of jna doesn't make any difference.
Having version numbers on jna doesn't make any difference.

I now understand some of the things I was doing wrong so I'll try again to see if it works on my Vista machine and to see if I can make it work with the new source files

Regards

Alex

**Comment by AlexBGar** [comment]
I have tried Example2 on my Vista machine and get the error:

java.lang.RuntimeException: SetupDiGetDeviceInterfaceDetail resulting in error 1784
  at purejavahidapi.windows.WindowsBackend.enumerateDevices(WindowsBackend.java:174) etc

On Windows 10, I now have Example2 running with the purejavahidapi source files. I have put a printout line in each od the methods and get the output 

DeviceRemovalHandler
callback
callback
callback
callback
callback
onInputReport: id 0 len 8 data 84 E8 6E AE A1 2C 01 00  Open = true
onInputReport: id 0 len 8 data 28 EA 36 8A 61 2D 00 00  Open = true
onInputReport: id 0 len 8 data 44 00 00 00 00 00 04 23  Open = true
onInputReport: id 0 len 8 data 92 E8 8A AF A0 2C 01 00  Open = true
onInputReport: id 0 len 8 data 36 EA 9B 89 59 2D 00 00  Open = true
callback
onDeviceChange
callback
onDeviceChange
onDeviceChangeRemoveComplete
onDeviceChangeArrivalOrRemoveComplete
handleDeviceRemoval

What can I do now to help to find out what is happening?

Alex

**Comment by nyholku** [comment]
Ok, now we are getting somewhere!

On Vista the error is 

    ERROR_INVALID_USER_BUFFER
    1784 (0x6F8)
    The supplied user buffer is not valid for the requested operation.

But let us leave that aside for the moment.

On Windows 10 then almost everything is now working, now we need to figure out why the execution does not reach line 114 of DeviceRemovalHandler.java

    m_WindowsBackend.deviceRemoved(deviceId);

i.e. basically which of the four nested 'if' statements fail.

Set a break point on 103

and single step to see where it fails.

None of those are supposed to fail ever so there is no error reporting. You might want to add an else clause to each if and call reportLastError() in case the call fails.

If get to line 113 note down the values of variables:

	char[] deviceIdChars 
	int[] deviceIdLen 
	String deviceId

**Comment by AlexBGar** [comment]
These are the values I get
 
 Char  =USB\VID_16D0&PID_044B\6&36B6332D&0&1

 Len  =37
 DeviceID  =USB\VID_16D0&PID_044B\6&36B6332D&0&1

**Comment by nyholku** [comment]
Good job.

So you get to line 113?

The values look perfectly reasonable.

Next thing is to add some print statements to WindowsBackend.java.

After line 77 add print statements to print out 'deviceId', 'path' and 'id' to see why 'if' in line 78 does not find the correct device.

**Comment by AlexBGar** [comment]
These are the outputs. To me, it looks like this is where the problem lies.

deviceID =USB\VID_16D0&PID_044B\6&36B6332D&0&1
Path     =\\?\hid#vid_16d0&pid_044b#7&7add44f&1&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
USB\VID_04F3&PID_024B\6&34D947EA&0&4  
id       =USB\VID_04F3&PID_024B\6&34D947EA&0&4

**Comment by nyholku** [comment]
Very strange, this does not compute at all!

'deviceID' is what we get from the OS when the device is unplugged and 'id' is what PureJavaHidApi recorded for the device when it was opened:

    deviceID =USB\VID_16D0&PID_044B\6&36B6332D&0&1
    id       =USB\VID_04F3&PID_024B\6&34D947EA&0&4

Totally different!

I guess VID=16D0 and PID=044B is correct for your device, can you confirm that?

Assuming so, then the logic used to find the device id when the devise is opened must be faulty.

This logic is in WindowsBackend.java in the loop on  lines 139-153.

Please do the following:

Remove the 'break' at line 151. 
Add a print statement after line 148 to output the value of 'parentId'. 
Add a print statement before line 139 to output the value of 'deviceID' .

Plugin the device and run your code and copy/paste values the enumeration code prints.

The logic in this code is that when a device is unplugged the OS gives us a USB device id but when the device is enumerated and opened the OS gives as a HID device id and we need a way to tie these together. So this loops tries to find the USB id related to the HID id by going up the device tree. 

Apparently something works differently in your system than mine. Maybe because you are on Windows 10 or your device is different.

The purpose of above changes is to get us the full hierarchy from the HID device up to the root device so we can figure out where the code logic fails and how to fix it.

**Comment by AlexBGar** [comment]
run:
deviceId in List =HID\VID_04F3&PID_024B&COL01\7&27AED151&0&0000

parentId =
parentId =
parentId =
parentId =
parentId =
parentId =
parentId =
parentId =
onInputReport: id 0 len 8 data AD E8 39 A6 A2 2C 01 00  Open = true

Above is the initial output from the system.
My device is VID=16D0 and PID=044B
VID_04F3&PID_024B is on my system and appears first when I use List separately. The manufacturer is Elan. I suspect it is the Touchpad, Touchscreen or Keyboard

**Comment by nyholku** [comment]
Thanks.

Something is not right here.

When you run your code the enumeration is called and we should see your device in those degug prints but I don't see it.

Your debug output only shows HID\VID_04F3&PID_024B but it should also show something like HID\VID_16D0&PID_044B. If it does not show that then I don't see how the device can be enumerated and opened and yet you show that it is reporting input reports. 

Hmm, I think I see the problem now. Looking at the code I see the enumeration does not correctly loop through all the devices so things get mixed up.  I will try to work on this tonight, should not be more than an hours work. I'll be back,

**Comment by nyholku** [comment]
Please try the latest (0.0.4) version that I just pushed.

**Comment by AlexBGar** [comment]
Hi - Tried version 4. It still doesn,t work on my machine. I am on holiday today. I'll try print statements again tomorrow - Alex

**Comment by AlexBGar** [comment]
Hi - In WindowsBackend.java I put print statements on lines 189 and 200. I didn't comment out any breaks. The print statements were

parentID =USB\VID_04F3&PID_024B\6&34D947EA&0&4
deviceId =HID\VID_04F3&PID_024B&COL01\7&27AED151&0&0000

The deviceId actually is a long array with empty entries. These are not my VID or PID values but do describe a device on my machine - the first on the list when I list them.

Hope that this helps

**Comment by nyholku** [comment]
Thanks, looks like my attempt to fix this did not work, we still get the wrong device in that loop. I will investigate further in the evening.

**Comment by nyholku** [comment]
Hi, sorry I've been absent, had a bit of cold/flu, now better.

So looking at your message, there is something strange.

The parentID and deviceID look correct as such because they describe a device in your system. However did you not also see your device printed out?

And if you did not I can't understand how you can open the device because this is the only place in the code (inside the `if (dfound)` (lines 183-219) ) where the device gets added to the list of enumerated devices and if it does not happen there then you can't open it.

Can you please double check what is going on.

Assuming your device was not found (and you could not open it) then we need to loop further up in the code, please add following after line 151:

    {
    if (!SetupDiEnumDeviceInfo(device_info_set, deviceIndex, devinfo_data))
        reportLastError();
    char[] deviceIdChars = new char[256];
    int[] deviceIdLen = { 0 };
    if (SetupDiGetDeviceInstanceId(device_info_set, devinfo_data, deviceIdChars, deviceIdChars.length, deviceIdLen))
        reportLastError();
    String deviceId = new String(deviceIdChars);
    System.out.println(deviceId);
    }
    String deviceId = new String(deviceIdChars);
    System.out.println(deviceId);
    }

and report back here thank you.

**Comment by AlexBGar** [comment]
Hi
My device opens.  The ParentID and DeviceID are printed out 5 times before the device starts working.
The inputs from the device are printed as expected but, when the device is removed, no message is given.

I'll try your latest print messages tomorrow

Alex

**Comment by nyholku** [comment]
Thanks for report.
Please try the additional printouts.
However, since you can open the device, then the existing printouts must already also show your device ... can you please copy the complete output from the test here?

**Comment by AlexBGar** [comment]
Attached are the print messages from tests using your version2 and version 4. Hope this helps

Alex

**Comment by AlexBGar** [comment]
Sorry, forgot the attachment

[outputs fro test v2 and v4.pdf](https://github.com/nyholku/purejavahidapi/files/202437/outputs.fro.test.v2.and.v4.pdf)

**Comment by nyholku** [comment]
Thanks. But the output does not make sense because the one and same device is printed seven times but the right device not. I can understand a bug where a wrong device is listed but how come the right device gets then opened?! Please add a print statement before line:
(somewhere around 220 in WindowsBackend.java):

     list.add(new HidDeviceInfo(path, devHandle, attrib));

add

     System.out.println("add device, path="+path);

**Comment by AlexBGar** [comment]
The output is in this text file. I have used version 0.0.2. Let me know if you want the same for v 0.0.4.
Note that the lines in this text file are wide - you have to scroll across to see them.

[TestV2 2.txt](https://github.com/nyholku/purejavahidapi/files/202658/TestV2.2.txt)

**Comment by nyholku** [comment]
Sorry I was not specific, please use 0.0.4 for all testing, the earlier version have a definite bug which was fixed in 0.0.4 which should work and we are trying to debug why it doesn't cause looking at the code over and over again I can't spot where the mix up happens.

**Comment by nyholku** [comment]
Oh yeas and keep the other printouts in place, you might as well add the long printout at 151 is asked for two days ago. And please include attach your modified WindowsBackend so I see exactly where the printouts are.

**Comment by AlexBGar** [comment]
Latest printouts attached. The WindowsBackend.java has been renamed as a txt file because of the attachment rules.
[testv4 2.txt](https://github.com/nyholku/purejavahidapi/files/202804/testv4.2.txt)
[WindowsBackend.txt](https://github.com/nyholku/purejavahidapi/files/202811/WindowsBackend.txt)

**Comment by nyholku** [comment]
Hi,

I see how it fails, but I don't know how the logic here is supposed to work because this logic comes from an example code (signal11 hidapi) that I followed. I've contacted the author to get some enlightenment.

Meanwhile I followed my own logic and modified the code (attached), so please try that and report back the output.



[WindowsBackend.txt](https://github.com/nyholku/purejavahidapi/files/203004/WindowsBackend.txt)

**Comment by AlexBGar** [comment]
Success at last - thanks.
There seems to be another problem somewhere but I will open another issue on that.

Alex

**Comment by nyholku** [comment]
Great, I thought it might because now the code makes sense to me and I can understand how it works. The nagging thing is that there must have be a reason in HIDAPI why it contained the logic I did not understand so this casts a doubt as to what am I missing with my simplistic approach. Oh well, I guess cross that bridge when we get there. I try to make a release before I leave for trip, I will be gone until May.

**Comment by nyholku** [comment]
Just pushed the changes, but could not test them, please report that it works for yuo.

**Comment by AlexBGar** [comment]
Initial test do work. Thanks. Enjoy your trip.

Alex

**Comment by nyholku** [comment]
Hi, thanks for the feedback and wishes. I'll close this now, don't hesitate to open a new issue if something arrises.
